apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}-masters
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  clusterIP: None
  ports:
    - port: 9300
      targetPort: 9300
  selector:
    app: {{ template "fullname" . }}
    type: master
