{{- if .Values.networkPolicy.enabled }}
kind: NetworkPolicy
apiVersion: {{ .Values.networkPolicy.apiVersion }}
metadata:
  name: {{ .Release.Name }}-master
  labels:
    app: {{ template "name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: {{ template "fullname" . }}-master
spec:
  podSelector:
    matchLabels:
      app: {{ template "name" . }}
      release: {{ .Release.Name }}
      component: {{ .Release.Name }}-master
  ingress:
    # Allow web access to the UI
    - ports:
      - port: {{ .Values.master.service.externalPort }}
    # Allow inbound connections from slave
    - from:
      - podSelector:
          matchLabels:
            "jenkins/{{ .Release.Name }}-agent": "true"
      ports:
      - port: {{ .Values.agentlistenerService.externalPort }}
{{- end }}
